services:
  - type: web
    name: library-strategic-priorities-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: AUTO_CREATE_TABLES
        value: true
      - key: AUTO_SEED_DATA
        value: true
